name: Update User Data on GitHub Pages

on:
  push:
    branches:
      - main  # یا هر شاخه‌ای که می‌خواهید

jobs:
  update-json:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the repository
        uses: actions/checkout@v2

      - name: Set up Python for script
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'

      - name: Install required dependencies
        run: |
          pip install requests

      - name: Get and update user data
        run: |
          import json
          import requests

          # خواندن فایل JSON موجود از گیت‌هاب
          url = "https://raw.githubusercontent.com/your-username/your-repo/main/data/users.json"
          response = requests.get(url)
          users = response.json()  # دریافت داده‌ها از فایل JSON

          # اضافه کردن اطلاعات جدید به لیست
          new_user_data = {"name": "John Doe", "email": "john@example.com"}
          users.append(new_user_data)

          # ذخیره اطلاعات جدید در GitHub
          new_json = json.dumps(users, indent=2)
          headers = {
            "Authorization": "token ${{ secrets.GITHUB_TOKEN }}",
            "Content-Type": "application/json"
          }

          # ارسال داده‌ها به فایل JSON در گیت‌هاب
          commit_url = f"https://api.github.com/repos/your-username/your-repo/contents/data/users.json"
          payload = {
            "message": "Update user data",
            "content": new_json.encode("utf-8").decode("latin1")  # تبدیل به base64
          }
          response = requests.put(commit_url, headers=headers, json=payload)

          if response.status_code == 200:
              print("Data updated successfully")
          else:
              print(f"Error: {response.status_code}")
